package com.bjit.common.rest.app.service.comosData.defaultdata;

public class DefaultMap {
//    public static String LOGICAL_SYSTEM_REFERENCE_TYPE = "RFLVPMLogicalSystemReference";
////    public static String PIPE_TYPE = "Piping_Logical_Pipe";
//    public static String PIPE_TYPE = "Piping_Line";
//    public static String VALVE_TYPE = "Piping_Logical_Valve";
//    public static String LOGICAL_PIPE_INSTRUMENT_TYPE = "Piping_Logical_Instrument";
//    public static String EQUIPMENT_TYPE = "EnsLogicalEquipment";
//    public static String LOGICAL_SYSTEM_INSTANCE_TYPE = "RFLVPMLogicalSystemInstance";
//    public static String LOGICAL_PIPE_INSTRUMENT_INSTANCE_TYPE = "Piping_Logical_Instrument_Inst";
//    public static String EQUIPMENT_INSTANCE_TYPE = "EnsLogicalEquipmentInst";
////    public static String PIPE_INSTANCE_TYPE = "Piping_Logical_Instrument_Inst";
//    public static String PIPE_INSTANCE_TYPE = "Piping_Line_Inst";
//    public static String VALVE_INSTANCE_TYPE = "Piping_Logical_Valve_Inst";
//    public static String REFERENCE_X_MIN = "0";
//    public static String REFERENCE_X_MAX = "504";
//    public static String REFERENCE_Y_MIN = "0";
//    public static String REFERENCE_Y_MAX = "336";
//    public static String REVISION = "1.1";
//    public static String POLICY = "VPLM_SMB_Definition";
//    public static String CURRENT = "IN_WORK";
//    public static String RESERVED_BY = "jklalrahab";
//    public static String OWNER = "jklalrahab";
//    public static String ORGANIZATION = "VALMET_INTERNAL";
//    public static String PROJECT = "GLOBAL_COMPONENTS_INTERNAL";
//    public static String LOGICAL_SYSTEM_REFERENCE_DISCIPLINE = "RFLVPMLogicalSystemReference";
//    public static String LOGICAL_SYSTEM_INSTANCE_DISCIPLINE = "RFLVPMLogicalSystemInstance";
//    public static String EQUIPMENT_DISCIPLINE = "EnsLogicalEquipment";
////    public static String PIPE_DISCIPLINE = "Piping_Logical_Pipe";
//    public static String PIPE_DISCIPLINE = "Piping_Line";
//    public static String VALVE_DISCIPLINE = "Piping_Logical_Part";
//    public static String INSTRUMENT_DISCIPLINE = "Piping_Logical_Instrument";
//    public static String EQUIPMENT_INSTANCE_DISCIPLINE = "EnsLogicalEquipmentInst";
//    public static String PIPE_INSTANCE_DISCIPLINE = "Piping_Line_Inst";
//    public static String VALVE_INSTANCE_DISCIPLINE = "Piping_Logical_Valve_Inst";
//    public static String DISPLAY_NAME = "TRUE";
//    public static String INSTANCE_X_MIN = "24";
//    public static String INSTANCE_X_MAX = "96";
//    public static String INSTANCE_Y_MIN = "144";
//    public static String INSTANCE_Y_MAX = "192";
//    public static String ORIGINATED_DATE = "10/06/21 :: 01:47:51 PM";
//    public static String MODIFIED_DATE = "10/06/21 :: 01:47:51 PM";
}