define("DS/ReportingPrintingUX/ReportingPrintingUX_it", {});
define("DS/ReportingPrintingUX/assets/nls/ReportingPrintingUX", {
    RP_LEGEND_HEADER: "Report Parameters",
    RP_LABEL_ITEM_NAME: "Item Name",
    RP_LABEL_REVISION: "Revision",
    RP_LABEL_REPORT_TYPE: "Report Type",
    RP_LABEL_REPORT_FORMAT: "Report Format",
    RP_LABEL_TEMPLATE_LANGUAGE: "Template Language",
    RP_LABEL_CONFIDENTIALITY: "Confidentiality",
    RP_LABEL_DOCTYPE: "Drawing Type",
    RP_LABEL_DRAWINGREQUIRED: "Print Drawing Info",
    RP_LABEL_SUMMARYREQUIRED: "Print Summary Report",
    RP_LABEL_BOM_LEVEL: "BOM Level",
    RP_LABEL_ATTRIBUTES: "Attributes",
    RP_LABEL_DELIVERY: "Print Delivery Info",
    RP_LABEL_MAIN_PROJ_TITLE: "Main Project Title",
    RP_LABEL_PSK: "Project Search Key",
    RP_LABEL_SUB_TITLE: "Subtitle",
    RP_LABEL_PRODUCT: "Product",
    RP_LABEL_SUBMIT: "Submit",
    RP_TOOLTIP_SELECT_ALL: "Select All",
    RP_TOOLTIP_INCREASE_BOM_LEVEL: "Incease BOM Level",
    RP_TOOLTIP_DECREASE_BOM_LEVEL: "Decrease BOM Level",
    RP_SELECT_ATTRIBUTES: "Include in Report",
    RP_DESELECT_ATTRIBUTES: "Exclude from Report",
    RP_TEXT_MBOM_ITEM_SEARCH: "Enter Manufacturing Assembly Item Name",
    RP_TEXT_EBOM_ITEM_SEARCH: "Enter Physical Product Item Name",
    RP_TEXT_SPR_ITEM_SEARCH: "Enter Manufacturing Assembly Item Name",
    RP_TEXT_MAIN_PROJ_TITLE: "Enter Main Project Title",
    RP_TEXT_PSK: "Enter Project Search Key",
    RP_TEXT_SUB_TITLE: "Enter Subtitle",
    RP_TEXT_PRODUCT: "Enter Product",
    RP_TEXT_BOM_LEVEL: "Level Beetween 0 and 99",
    RP_TEXT_ATTRIBUTE_SEARCH: "Search",
    RP_ALERT_ITEM_NAME: "Please provide 'Item Name' properly!",
    RP_ALERT_BOM_LEVEL: "Please provide 'BOM Level' properly!",
    RP_ALERT_ITEM_NAME_BOM_LEVEL: "Please provide 'Item Name' and 'BOM Level' properly!",
    RP_ALERT_ATTRIBUTE_LIST: "Please select 'Attribute' from the list!",
    RP_ALERT_DROP_MULTIPLE_ITEM: "Multiple Item is not allowed!",
    RP_ALERT_DROP_MBOM_ITEM: "Drop Manufacturing Assembly Item!",
    RP_ALERT_DROP_EBOM_ITEM: "Drop Physical Product Item!",
    RP_ALERT_INVALID_INPUT: "Please provide valid Inputs!",
    RP_ALERT_PRIMARY_SECONDARY_LANGUAGE_SAME: "Primary and Secondary Language can not be same. Please change in Preference Settings!",
    RP_ERROR_MESSAGE_SPECIAL_CHARACTER: "Special characters not allowed!",
    RP_ERROR_MESSAGE_MAX_LENGTH: "Maximum {0} characters allowed!",
    RP_REPORT_GENERATION_OK: "Report Generation Completed!",
    RP_REPORT_GENERATION_FAILED: "Report Generation Failed!",
    RP_REPORT_GENERATION_ON_GOING: "Report is preparing... please wait!",
	SRP_MANDATORY_ATTRIBUTE_ERROR: "Name and Title are Mandatory Attribute",
    RP_REPORT_GENERATION_BACKGROUND_MESSAGE: "Report will be processed in background. Report download link will be sent in mail after completion of the process",
    RP_ALERT_DOC_TYPE: "Please select drawing type"
});